### ISSUE TITLE
Question about model.py

### ISSUE THREAD

**Issue by coukei123** [30stomercury/Interaction-aware_Attention_Network#1]
In the model.py file, I find a problem.It is the code:
        "paddings =  (mask_att)*(-1e8)
         vu = tf.where(tf.equal(mask_att, 0), paddings, vu)"
I think the "paddings" is no useful,in other words,it doesn't  work.Because "mask_att" variable is a matrix about "0" and "1", "paddings" variable is 0 in where "mask_att" is 0, -1e8 where "mask_att" is 1.Then variable "vu" equal to 
        "vu = tf.where(tf.equal(mask_att, 0), mask_att, vu)"

**Comment by 30stomercury** [comment]
Hi, you're right! It should be ```paddings = (mask_att)*(-10e8)```  instead.
The purpose of vu = tf.where(tf.equal(mask_att, 0), paddings, vu) is to mask the attention weight in following softmax function.
I'll modified that line soon.

**Comment by coukei123** [comment]
Thank you for your reply!But I don't known the difference between muliplying (-10e8) and (-1e8)?And I think "paddings" should be a tensor have the same shape with "mask_att",but all position is (-1e8).In tihis way,when "mask_att" in 0 position, the output "vu" will be (-1e8) which after softmax will be 0.

**Comment by 30stomercury** [comment]
1. Sorry -1e8 and -10e8 is the same, I did a dumb thing :P.
2. Yes, paddings" should be a tensor have the same shape with mask_att, but all position is (-1e8) to guarantee the value after softmax is 0.

**Comment by coukei123** [comment]
I am sorry too!Your code doesn't have problem.It is my mistake which I have some wrong with my pycharm resulting I don't look the "tf.ones_like“ before.Thank you for your patient answer!

**Comment by 30stomercury** [comment]
You're welcome,  feel free to ask me if you have any question.
