### ISSUE TITLE
missing feat_pooled.pkl

### ISSUE THREAD

**Issue by pbrusco** [30stomercury/Interaction-aware_Attention_Network#5]
Hi! Thanks for sharing this code. 

I was able to run the `preprocess.py` and `extractSmile.py` scripts on the data folder. 
Then, I'm having some trouble running the `script_train.py` script since I don't know how to generate the "feat_pooled.pkl". 

I've seen that you name `data.py` to have a function to generate those, but I don't know how to use it. 

Is there a missing script? Or am I missing something? 

Thanks a lot

**Comment by 30stomercury** [comment]
Hi! Thanks for reporting.
I'll update this repo these days, I'm currently busy in Interspeech20 submission.
In short, feat_pooled.pkl is just a pooled version of extracted features. You can run function mean_pool() in data.py, in this paper we set n=5.

I'll update a clean version ASAP. 

Again, thanks for reporting.

**Comment by pbrusco** [comment]
Hi!

Thanks for your answer. I tried to run the mean_pool function but I don't know which is the parameter I should pass to it. 

Thanks a lot.

**Comment by 30stomercury** [comment]
Hi, I've upload a simple script of feature pooling.
Also, I added the descriptions of arguments in mean_pool() here:
https://github.com/30stomercury/Interaction-aware_Attention_Network/blob/be85aac9fa1e60e08a0259edbead3d301fac82e4/data.py#L11

Thanks.

**Comment by 30stomercury** [comment]
If you find this project helpful for your research, please consider to cite our paper!

**Comment by pbrusco** [comment]
Hi, thank you for the changes. Of course if I use this as a baseline it will be cited!  

I've add some missing import (from argparse import ArgumentParser) and then run the following command (be careful that the readme version is updated):

```python3 pool_feats.py --input_file data/feat_all.pkl --output_file data/feat_pooled.pkl --feat_dim 45 --step 5 --max_step 500```

But, can you please provide the specific steps and parameters for reproducing your work in the README :). 

Ideally, a run.sh that makes all the steps. 

I know it can be a lot to ask, but I find it is the only way to be sure we are doing exactly as you do. 

Thanks a lot.

**Comment by 30stomercury** [comment]
Yes, I have my run.sh. I'll upload it soon. 
I just finished my is20 submission, so don't hesitate to ask me if there's anything you need.

**Comment by 30stomercury** [comment]
Hi, you can pull my new commit. I also run an experiment, the results can be found at ```outputs``` 
 folder.
