### ISSUE TITLE
script arguments outdated

### ISSUE THREAD

**Issue by pbrusco** [30stomercury/Interaction-aware_Attention_Network#6]
When running 
`python3 script_train.py -lr 0.0001 -batch_size 64 -keep_proba 0.9  -seq_dim 512  -save_path ./model/iaan/ > out.txt`

I get 
`script_train.py: error: unrecognized arguments: -save_path ./model/iaan/`

Is there a new version of the script that is not commited? 

Thanks

**Comment by 30stomercury** [comment]
Yes, I'll update it soon. I'll let you know once I commit!
Sorry for the late update.

Brian

**Comment by 30stomercury** [comment]
Hi! I've updated my script. Hope you find it useful.

Thanks
