### ISSUE TITLE
 No such file or directory: 'data/feats.pkl'

### ISSUE THREAD

**Issue by linxue123** [30stomercury/Interaction-aware_Attention_Network#7]
How do I find this file? How is this file generated? What does IEMOCAP do with this data set? Is there pre-processing? In which directory?

**Comment by 30stomercury** [comment]
Hi,

Please refer to `run.sh`.

**Comment by linxue123** [comment]
您好，很抱歉打扰您了，我是一个新手。我想请问一下我在训练过程中遇到以下问题，该怎么解决呢，还有就是parser.add_argument('--model_dir', dest='model_dir', default='./model/iaan/', type=str)，model/iaan这个文件没有，怎么生成呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "30stomercury/Interaction-Aware-Attention-Network"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月13日(星期一) 晚上9:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [30stomercury/Interaction-Aware-Attention-Network]  No such file or directory: 'data/feats.pkl' (#7)





 
Hi,
 
Please refer to run.sh.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
